### PR TITLE
add eip712 definitions for dispatch.xyz

### PR DESCRIPTION
**Pull request by ryan-lambert-IEX**
Adds eip712 definitions for dispatch.xyz. 

We use eip712 to sign a message -> pass to Lens Protocol -> pass to their contract (message they are asked to sign defined in the PR).

Thank you!

```
$ python scripts/validate_files.py --debug
INFO:__main__:Running validation for json
INFO:validation.validators:Result: 457 valid, 0 invalid
INFO:__main__:Running validation for endlines
INFO:validation.validators:Result: 457 valid, 0 invalid
INFO:__main__:Running validation for eip712_schema
INFO:validation.validators:Result: 1 valid, 0 invalid
INFO:__main__:Running validation for polygon_b2c
INFO:validation.validators:Result: 13 valid, 0 invalid
INFO:__main__:Running validation for bsc_b2c
INFO:validation.validators:Result: 5 valid, 0 invalid
INFO:__main__:Running validation for ethereum_ropsten_b2c
INFO:validation.validators:Result: 2 valid, 0 invalid
INFO:__main__:Running validation for ethereum_ropsten_parsers
INFO:validation.validators:Result: 0 valid, 0 invalid
INFO:__main__:Running validation for ethereum_goerli_b2c
INFO:validation.validators:Result: 2 valid, 0 invalid
INFO:__main__:Running validation for ethereum_goerli_parsers
INFO:validation.validators:Result: 0 valid, 0 invalid
INFO:__main__:Running validation for ethereum_b2c
INFO:validation.validators:Result: 20 valid, 0 invalid
INFO:__main__:Running validation for ethereum_parsers
INFO:validation.validators:Result: 3 valid, 0 invalid
INFO:__main__:Running validation for ethereum_eip712
INFO:validation.validators:Result: 1 valid, 0 invalid
(ledger-asset-dapps)
```

### CODE REVIEW

**Comment by ryan-lambert-IEX** [comment]
@adrienlacombe-ledger done!

**Comment by adrienlacombe-ledger** [comment]
ah sorry @ryan-lambert-IEX filename should be `eip712.json` then I will merge :)

**Comment by ryan-lambert-IEX** [comment]
@adrienlacombe-ledger done - thank you and apologies! Should have caught that one

**Comment by adrienlacombe-ledger** [comment]
np :)

**Comment by ryan-lambert-IEX** [comment]
@adrienlacombe-ledger had to also remove from the `name` field - should be g2g now

**Pull request merged**
