### PR TITLE
update stader, kelp abis

### PR DESCRIPTION
**Pull request by manoj9april**
- added abi for Kelp Deposit Pool
- updated selectors for ethx deposit and request_withdraw

### CODE REVIEW

**Review by mohammed-ledger — APPROVED** [review]

**Review by fsamier — DISMISSED** [review]
LGTM

**Comment by mohammed-ledger** [comment]
@manoj9april Thank you for submitting the PR.  It looks good to me, In order to be able to merge the PR can you please 
- change `ethereum/stader/abis/0x036676389e48133b63a802f8635ad39e752d375d.json` to ethereum/stader/abis/0x036676389e48133b63a802f8635ad39e752d375d.abi.json` to 
- Sign commits. Main requires all commits to be signed

Thank you

**Comment by manoj9april** [comment]
@mohammed-ledger @fsamier Thank you for the review.
raised a similar new PR through github web interface so that it contains signed commits.
PR : #181 
Please review that and feel free to close this.

**Comment by fsamier** [comment]
Closed against https://github.com/LedgerHQ/ledger-asset-dapps/pull/181

**Pull request closed without merging**
