### PR TITLE
Rarible eip-712 ethereum, polygon

### PR DESCRIPTION
**Pull request by disenotov**

### CODE REVIEW

**Review by YBadiss — COMMENTED** [review]
All addresses need to be in lower case in these files, that should fix the validation 👍

**Comment by disenotov** [comment]
> All addresses need to be in lower case in these files, that should fix the validation 👍

thanks, fixed addresses

**Comment by adrienlacombe-ledger** [comment]
@disenotov please run `python scripts/validate_files.py --debug` and commit, thank you!

**Comment by disenotov** [comment]
sorry, i don't know much about python and can't make the script work :)
so, if i understand correctly, i need to:
- install python 3.9
- install pipenv
- install dependencies from pipfile
- execute script

but when i do "pipenv install" i get this error 
```
No such file or directory: '/Users/ds/.local/share/virtualenvs/ledger-asset-dapps-X8NUJxfs/bin/python'
```
do you know what could be the problem? maybe i'm missing something? it looks like i'm installing python or pipenv wrong.

i tried reinstalling everything and it still doesn't work :)

**Comment by adrienlacombe-ledger** [comment]
np @disenotov please merge this https://github.com/disenotov/ledger-asset-dapps/pull/1

**Pull request merged**
