### PR TITLE
Add Brick Towers plugin to Holesky network

### PR DESCRIPTION
**Pull request by skisel-bt**

### CODE REVIEW

**Review by jnicoulaud-ledger — APPROVED** [review]

**Comment by jnicoulaud-ledger** [comment]
@skisel-bt you need to GPG sign your commits, please check https://docs.github.com/en/authentication/managing-commit-signature-verification

**Comment by skisel-bt** [comment]
Actually my commits are signed, maybe rebase rewrote my commits, I will try to rebase myself and see what happens.

**Comment by skisel-bt** [comment]
@jnicoulaud-ledger I think now my commit is Verified, so the issue was that rebase somehow removed the verification.

**Comment by skisel-bt** [comment]
auto-merge is unfortunately is gone as I rebased.. @jnicoulaud-ledger please merge

**Comment by jnicoulaud-ledger** [comment]
NP, merging

**Pull request merged**
