### PR TITLE
add stakekit descriptors

### PR DESCRIPTION
**Pull request by Z4karia**

### CODE REVIEW

**Comment by jnicoulaud-ledger** [comment]
For reference, descriptors previously removed in #165 because of contract collisions
https://ledger.slack.com/archives/C02JFKVJHA6/p1710262115450869?thread_ts=1707216555.037699&cid=C02JFKVJHA6

**Review by jnicoulaud-ledger — CHANGES_REQUESTED** [review]
@Z4karia Thanks, there are a few validation errors, could you check it ? https://github.com/LedgerHQ/ledger-asset-dapps/pull/185/checks#step:6:14

Let me know if unclear for you

**Comment by Z4karia** [comment]
Hello @jnicoulaud-ledger, the issues have been fixed.

- The contract "0x794a61358D6845594F94dc1DB02A252b5b4814aD" had slightly different implementations across the 4 networks it's deployed on. We used the latest version on all abis.

- The contract "0x889edc2edab5f40e902b864ad4d7ade8e412f9b1" had selectors that had already been declared in the Lido plugin (requestWithdrawals[0xd6681042] and claimWithdrawals[0xe3afe0a3]). This address was not on the contract list we were provided when removing the redundant selectors. We will remove them from the StakeKit plugin.

- The abis have been formatted with the python script

**Review by jnicoulaud-ledger — APPROVED** [review]
LGTM, thanks! We will sign and deploy it next week

**Pull request merged**
