### PR TITLE
add libertify on polygon

### PR DESCRIPTION
**Pull request by bmarcot**

### CODE REVIEW

**Comment by noudin-ledger** [comment]
CI is red, file is not well formatted and is missing some fields

**Comment by bmarcot** [comment]
> CI is red, file is not well formatted and is missing some fields

Fixed.

**Comment by adrienlacombe-ledger** [comment]
@noudin-ledger ok for you? ty ty

**Review by noudin-ledger — APPROVED** [review]

**Comment by adrienlacombe-ledger** [comment]
@bmarcot can you sign your commit please? ty

**Comment by bmarcot** [comment]
> @bmarcot can you sign your commit please? ty

Done.

**Pull request merged**
