### PR TITLE
okx : b2c.json and abi

### PR DESCRIPTION
**Pull request by hhhu19**
Added b2c.json file and abi on：
avalanche
base
bsb
fantom
opt
polygon
polygonzkevm

### CODE REVIEW

**Comment by adrienlacombe-ledger** [comment]
lower case only in the contract addresses please @hhhu19 ty!

**Comment by adrienlacombe-ledger** [comment]
in the files names as well @hhhu19 sorry for that

**Comment by hhhu19** [comment]
> in the files names as well @hhhu19 sorry for that

The modification has been completed, thanks

**Comment by adrienlacombe-ledger** [comment]
> > in the files names as well @hhhu19 sorry for that
> 
> The modification has been completed, thanks

please run `pipenv run validate_files` and commit the updated files

**Comment by hhhu19** [comment]
> > > in the files names as well @hhhu19 sorry for that
> > 
> > 
> > The modification has been completed, thanks
> 
> please run `pipenv run validate_files` and commit the updated files

ok

**Comment by adrienlacombe-ledger** [comment]
> > > > in the files names as well @hhhu19 sorry for that
> > > 
> > > 
> > > The modification has been completed, thanks
> > 
> > 
> > please run `pipenv run validate_files` and commit the updated files
> 
> ok

looks like you need to run it once more cf https://github.com/LedgerHQ/ledger-asset-dapps/actions/runs/7273764991/job/19818753908?pr=160#step:6:15

**Pull request merged**
