### PR TITLE
Add SmurfSociety config for EIP 712

### PR DESCRIPTION
**Pull request by seb-blue**

### CODE REVIEW

**Comment by adrienlacombe-ledger** [comment]
hi @seb-blue what you committed has nothing to do with 712, you need to commit an eip712.json

**Review by adrienlacombe-ledger — CHANGES_REQUESTED** [review]
please commit an eip712.json

**Comment by seb-blue** [comment]
@adrienlacombe-ledger Sorry, but I've followed the docs you provided... Can you direct me to what's really required please.

**Comment by adrienlacombe-ledger** [comment]
which doc @seb-blue? what are you trying to achieve?

**Comment by jnicoulaud-ledger** [comment]
Hi, I am closing this PR as it has been stale for a long time, please reopen it if needed.

**Pull request closed without merging**
