### PR TITLE
Add Brick Towers plugin to Mainnet network

### PR DESCRIPTION
**Pull request by skisel-bt**

### CODE REVIEW

**Comment by jnicoulaud-ledger** [comment]
@skisel-bt can you indicate me who is your contact at Ledger ?

**Comment by skisel-bt** [comment]
@jnicoulaud-ledger I am in the contact with Gaspard Broustine through Discord

**Comment by rhofacker-bt** [comment]
@jnicoulaud-ledger I am seeing a client of ours tomorrow to stake ETH with us via his Ledger Nano X using the Brick Towers clear-signing plugin. Does this work from a publishing perspective on your side?

**Review by jnicoulaud-ledger — APPROVED** [review]

**Comment by jnicoulaud-ledger** [comment]
@rhofacker-bt It will be too short notice, sorry. This should be signed and published early next week.

**Comment by rhofacker-bt** [comment]
Ok, thanks for coming back. That is of course sad to hear, then I have to educate on the security messages that look quite scary :D

**Comment by rhofacker-bt** [comment]
So it worked with blind signing today, looking forward for my client to use clear-signing next week.

**Comment by rhofacker-bt** [comment]
@jnicoulaud-ledger could you let us know once the extra step is finished on your end? Thanks a lot and have a good week!

**Pull request merged**
