### PR TITLE
Paraswap bsc

### PR DESCRIPTION
**Pull request by alacombe-ledger**
@pscott can you please review?
cc @gre to validate the importer is still working
cc @YBadiss for the signatures which shouldn't change theoretically
:pray: thank you gentlemen

### CODE REVIEW

**Comment by gre** [comment]
> cc @gre to validate the importer is still working

yes it will still be working because this are just new files that are not yet recognized by this importer =)

**Review by SnearK6354 — APPROVED** [review]

**Comment by FabriceDautriat** [comment]
don't mind the SnearK6354 approval, it's from me, with my personal email.

**Comment by FabriceDautriat** [comment]
@gre we need to be able to import the new data. Can you update the importer accordingly?

**Review by FabriceDautriat — APPROVED** [review]

**Comment by alacombe-ledger** [comment]
@pscott have you been able to take a look? Thank you!

**Review by pscott — APPROVED** [review]
:approved:

**Pull request merged**
